// Landing page text, written for farmers and the public: no model names,
// technical terms or statistics. French is the default; English and Arabic
// can be chosen. Every claim describes what the platform does today.
// French punctuation uses a no-break space (U+00A0) before ? : ; and !.
export const COPY = {
  fr: {
    skip: 'Aller au contenu',
    navLabel: 'Sections de la page',
    nav: [['forecast', 'Prix attendus'], ['weather', 'Météo'], ['photos', 'Examen des photos']],
    signIn: 'Se connecter',

    intro: {
      title: 'Aide à la décision pour les producteurs de cerises de la région Fès‑Meknès',
      body: 'SweetCherry aide les producteurs de Sefrou, Azrou, Ifrane, El Hajeb et Taounate à connaître le prix attendu des cerises sur les marchés de Casablanca, Rabat et Marrakech, à suivre la météo des prochains jours dans leur région et à obtenir l’avis d’un agronome sur les photos de feuilles et de fruits atteints.',
      register: 'Créer un compte producteur',
      expertPrompt: 'Agronome ?',
      expertLink: 'Demander un compte expert',
      expertNote: 'L’équipe de la plateforme vérifie votre justificatif avant d’activer le compte.',
      closedTitle: 'Inscriptions suspendues',
      closedNote: 'Les nouvelles inscriptions reprendront à l’ouverture de la prochaine session. Si vous avez déjà un compte, connectez-vous.',
    },

    figure: {
      alt: 'Vue de l’espace de la plaine du Saïss et du Moyen Atlas, avec Fès, Meknès et les forêts de cèdres au sud d’Ifrane et d’Azrou.',
      pinsLabel: 'Les cinq zones sur l’image',
      caption: 'La plaine du Saïss et le Moyen Atlas vus de l’espace (image de la NASA).',
      tempsAt: (time) => `Températures actuelles, mises à jour à ${time}.`,
      tempsError: 'Impossible de charger les températures actuelles.',
      scale: '25 km',
      reference: { fes: 'Fès', meknes: 'Meknès' },
    },

    forecast: {
      title: 'Prix attendu des cerises',
      lead: 'Pour chaque qualité et chaque marché, SweetCherry estime le prix le plus probable semaine après semaine, avec un prix bas et un prix haut, pour que le producteur prépare une semaine difficile comme une semaine normale.',
      grade: 'Qualité',
      market: 'Marché',
      markets: { M01: 'Casablanca', M02: 'Rabat', M03: 'Marrakech' },
      unit: 'DH/kg',
      loading: 'Chargement des prix attendus…',
      error: 'Impossible de charger les prix attendus. Rechargez la page dans un instant.',
      empty: 'Pas encore de prix attendus pour ce choix.',
      today: 'Aujourd’hui',
      legendMedian: 'Prix le plus probable',
      legendRange: 'Fourchette attendue',
      legendPast: 'Semaines passées',
      chartLabel: (grade, market) => `Prix hebdomadaire attendu des cerises de qualité ${grade} sur le marché de ${market}.`,
      thisWeek: 'Cette semaine',
      median: 'Prix le plus probable',
      medianNote: 'Planifiez vos ventes sur ce prix.',
      low: 'Si le marché est faible',
      lowNote: 'Vérifiez que vos coûts restent couverts même à ce prix.',
      high: 'Si le marché est fort',
      highNote: 'Possible, mais ne comptez pas dessus.',
      ended: (date) => `Les prix publiés couraient jusqu’au ${date}. Les nouveaux apparaîtront ici dès leur publication.`,
      notStarted: (date) => `Les prix publiés commencent le ${date}.`,
      updated: (date) => `Prix mis à jour le ${date}.`,
    },

    weather: {
      title: 'La météo dans les cinq zones',
      lead: 'Aujourd’hui et les deux prochains jours dans chaque zone. Dans leur compte, les producteurs reçoivent aussi les alertes de gel, de chaleur et de pluie pour leur zone.',
      caption: 'Température maximale puis minimale de chaque jour.',
      region: 'Zone',
      now: 'Maintenant',
      today: 'Aujourd’hui',
      rain: 'Pluie probable',
      frost: 'Gel possible',
      heat: 'Très chaud',
      loading: 'Chargement de la météo…',
      error: 'Impossible de charger la météo.',
    },

    photos: {
      title: 'Les photos du terrain sont examinées par un agronome avant tout conseil',
      body: [
        'Le producteur envoie depuis son téléphone la photo d’une feuille ou d’un fruit atteint. Un agronome l’examine, identifie le problème et sa gravité, et indique quoi faire ; la réponse apparaît dans le compte du producteur. Il peut aussi poser une question écrite ou vocale et poursuivre l’échange avec le même expert.',
        'Chaque photo examinée par les experts aide à entraîner le système de SweetCherry qui reconnaît les maladies des feuilles de cerisier sur photo. Ce système est encore en test : les conseils que reçoivent les producteurs viennent toujours d’un expert.',
      ],
      diseasesTitle: 'Ce que le système reconnaît',
      diseases: ['Feuilles saines', 'Oïdium', 'Taches brunes', 'Brûlure des feuilles', 'Taches pourpres', 'Criblure'],
    },

    footer: {
      about: 'Aide à la décision pour les producteurs de cerises de la région Fès‑Meknès.',
      account: 'Compte',
      register: 'Créer un compte producteur',
      expert: 'Demander un compte expert',
      sources: 'Sources',
      sourceList: [
        { before: 'Image satellite : ', link: 'NASA Worldview', href: 'https://worldview.earthdata.nasa.gov/', after: '.' },
        { before: 'Données météo : ', link: 'Open-Meteo.com', href: 'https://open-meteo.com/', after: '.' },
      ],
    },
  },

  en: {
    skip: 'Skip to content',
    navLabel: 'Page sections',
    nav: [['forecast', 'Expected prices'], ['weather', 'Weather'], ['photos', 'Photo review']],
    signIn: 'Sign in',

    intro: {
      title: 'Decision support for cherry growers in the Fès‑Meknès region',
      body: 'SweetCherry helps growers in Sefrou, Azrou, Ifrane, El Hajeb and Taounate see what cherries are expected to sell for in the Casablanca, Rabat and Marrakech markets, follow the weather for the coming days in their area, and get an agronomist’s opinion on photos of affected leaves and fruit.',
      register: 'Create a grower account',
      expertPrompt: 'Agronomist?',
      expertLink: 'Apply for an expert account',
      expertNote: 'The platform team checks your credentials before the account is activated.',
      closedTitle: 'Registration is paused',
      closedNote: 'New registrations will reopen with the next intake. If you already have an account, sign in.',
    },

    figure: {
      alt: 'View from space of the Saïss plain and the Middle Atlas, showing Fès, Meknès and the cedar forests south of Ifrane and Azrou.',
      pinsLabel: 'The five areas on the image',
      caption: 'The Saïss plain and the Middle Atlas seen from space (NASA image).',
      tempsAt: (time) => `Temperatures now, updated ${time}.`,
      tempsError: 'Current temperatures could not be loaded.',
      scale: '25 km',
      reference: { fes: 'Fès', meknes: 'Meknès' },
    },

    forecast: {
      title: 'Expected cherry prices',
      lead: 'For each grade and market, SweetCherry estimates the most likely price week by week, with a low and a high price, so a grower can plan for a difficult week as well as a normal one.',
      grade: 'Grade',
      market: 'Market',
      markets: { M01: 'Casablanca', M02: 'Rabat', M03: 'Marrakech' },
      unit: 'MAD/kg',
      loading: 'Loading expected prices…',
      error: 'Expected prices could not be loaded. Reload the page in a moment.',
      empty: 'No expected prices for this choice yet.',
      today: 'Today',
      legendMedian: 'Most likely price',
      legendRange: 'Expected range',
      legendPast: 'Past weeks',
      chartLabel: (grade, market) => `Expected weekly price for grade ${grade} cherries in the ${market} market.`,
      thisWeek: 'This week',
      median: 'Most likely price',
      medianNote: 'Plan your sales on this price.',
      low: 'If the market is weak',
      lowNote: 'Make sure your costs are covered even at this price.',
      high: 'If the market is strong',
      highNote: 'Possible, but don’t count on it.',
      ended: (date) => `The published prices ran until ${date}. New ones will appear here when they are published.`,
      notStarted: (date) => `The published prices start on ${date}.`,
      updated: (date) => `Prices last updated ${date}.`,
    },

    weather: {
      title: 'Weather in the five areas',
      lead: 'Today and the next two days in each area. Growers also get frost, heat and rain warnings for their own area in their account.',
      caption: 'Each day’s high, then low temperature.',
      region: 'Area',
      now: 'Now',
      today: 'Today',
      rain: 'Rain likely',
      frost: 'Frost possible',
      heat: 'Very hot',
      loading: 'Loading the weather…',
      error: 'The weather could not be loaded.',
    },

    photos: {
      title: 'Field photos are checked by an agronomist before any advice',
      body: [
        'A grower sends a photo of an affected leaf or fruit from their phone. An agronomist examines it, identifies the problem and how serious it is, and writes what to do; the answer appears in the grower’s account. Growers can also ask a written or spoken question and keep talking with the same expert.',
        'Every photo the experts review helps train SweetCherry’s system for recognising cherry leaf diseases from pictures. The system is still being tested, so the advice growers receive always comes from an expert.',
      ],
      diseasesTitle: 'What the system recognises',
      diseases: ['Healthy leaves', 'Powdery mildew', 'Brown spot', 'Leaf scorch', 'Purple leaf spot', 'Shot hole'],
    },

    footer: {
      about: 'Decision support for cherry growers in the Fès‑Meknès region.',
      account: 'Account',
      register: 'Create a grower account',
      expert: 'Apply as an expert',
      sources: 'Sources',
      sourceList: [
        { before: 'Satellite image: ', link: 'NASA Worldview', href: 'https://worldview.earthdata.nasa.gov/', after: '.' },
        { before: 'Weather data: ', link: 'Open-Meteo.com', href: 'https://open-meteo.com/', after: '.' },
      ],
    },
  },

  ar: {
    skip: 'انتقل إلى المحتوى',
    navLabel: 'أقسام الصفحة',
    nav: [['forecast', 'الأسعار المتوقعة'], ['weather', 'الطقس'], ['photos', 'مراجعة الصور']],
    signIn: 'تسجيل الدخول',

    intro: {
      title: 'منصة دعم القرار لمزارعي الكرز في جهة فاس مكناس',
      body: 'يساعد SweetCherry مزارعي صفرو وآزرو وإفران والحاجب وتاونات على معرفة السعر المتوقع للكرز في أسواق الدار البيضاء والرباط ومراكش، ومتابعة طقس الأيام القادمة في منطقتهم، وأخذ رأي خبير زراعي في صور الأوراق والثمار المصابة.',
      register: 'إنشاء حساب مزارع',
      expertPrompt: 'خبير زراعي؟',
      expertLink: 'قدّم طلب حساب خبير',
      expertNote: 'يراجع فريق المنصة وثيقة الاعتماد قبل تفعيل الحساب.',
      closedTitle: 'التسجيل متوقف مؤقتاً',
      closedNote: 'سيُفتح التسجيل من جديد مع الدفعة القادمة. إن كان لديك حساب، سجّل الدخول.',
    },

    figure: {
      alt: 'صورة من الفضاء لسهل سايس والأطلس المتوسط، تظهر فيها مدينتا فاس ومكناس وغابات الأرز جنوب إفران وآزرو.',
      pinsLabel: 'المناطق الخمس على الصورة',
      caption: 'سهل سايس والأطلس المتوسط كما يظهران من الفضاء (صورة من NASA).',
      tempsAt: (time) => `الحرارة الآن، آخر تحديث ${time}.`,
      tempsError: 'تعذّر تحميل الحرارة الآن.',
      scale: '25 كم',
      reference: { fes: 'فاس', meknes: 'مكناس' },
    },

    forecast: {
      title: 'سعر الكرز المتوقع',
      lead: 'لكل جودة ولكل سوق، يقدّر SweetCherry السعر الأرجح أسبوعاً بأسبوع، مع سعر أدنى وسعر أعلى متوقعين، حتى يخطط المزارع للأسبوع الصعب كما يخطط للأسبوع العادي.',
      grade: 'الجودة',
      market: 'السوق',
      markets: { M01: 'الدار البيضاء', M02: 'الرباط', M03: 'مراكش' },
      unit: 'درهم/كغ',
      loading: 'جارٍ تحميل الأسعار المتوقعة…',
      error: 'تعذّر تحميل الأسعار المتوقعة الآن. أعد تحميل الصفحة بعد قليل.',
      empty: 'لا توجد أسعار متوقعة لهذا الاختيار بعد.',
      today: 'اليوم',
      legendMedian: 'السعر الأرجح',
      legendRange: 'المجال المتوقع',
      legendPast: 'أسابيع مضت',
      chartLabel: (grade, market) => `السعر الأسبوعي المتوقع لكرز الجودة ${grade} في سوق ${market}.`,
      thisWeek: 'هذا الأسبوع',
      median: 'السعر الأرجح',
      medianNote: 'خطّط مبيعاتك على هذا السعر.',
      low: 'إذا ضعف السوق',
      lowNote: 'تأكد أن تكاليفك مغطاة حتى لو نزل السعر إلى هنا.',
      high: 'إذا تحسّن السوق',
      highNote: 'ممكن، لكن لا تبنِ عليه التزاماتك.',
      ended: (date) => `انتهت مدة التوقعات المنشورة في ${date}، وستظهر التوقعات الجديدة هنا عند نشرها.`,
      notStarted: (date) => `تبدأ التوقعات المنشورة في ${date}.`,
      updated: (date) => `آخر تحديث للتوقعات: ${date}.`,
    },

    weather: {
      title: 'الطقس في المناطق الخمس',
      lead: 'حالة الطقس اليوم واليومين القادمين في كل منطقة. ويتلقى المزارع في حسابه تنبيهات الصقيع والحرارة والمطر الخاصة بمنطقته.',
      caption: 'الحرارة الكبرى ثم الصغرى لكل يوم.',
      region: 'المنطقة',
      now: 'الآن',
      today: 'اليوم',
      rain: 'مطر مرجّح',
      frost: 'صقيع محتمل',
      heat: 'حر شديد',
      loading: 'جارٍ تحميل الطقس…',
      error: 'تعذّر تحميل الطقس الآن.',
    },

    photos: {
      title: 'صور الحقل يراجعها خبير قبل أي نصيحة',
      body: [
        'يرسل المزارع من هاتفه صورة للورقة أو الثمرة المصابة، فيفحصها خبير زراعي، ويحدد المشكلة ومدى خطورتها، ويكتب ما ينبغي فعله. وتظهر النتيجة في حساب المزارع. ويمكنه أيضاً أن يطرح سؤالاً مكتوباً أو صوتياً ويتابع الحديث مع الخبير نفسه.',
        'كل صورة يراجعها الخبراء تساعد في تدريب نظام SweetCherry للتعرف على أمراض أوراق الكرز من الصور. النظام ما زال في مرحلة التجربة، لذلك تأتي النصيحة التي تصل إلى المزارع دائماً من خبير.',
      ],
      diseasesTitle: 'ما يتعرف عليه النظام',
      diseases: ['الأوراق السليمة', 'البياض الدقيقي', 'التبقع البني', 'حرق الأوراق', 'التبقع الأرجواني', 'ثقب الرصاص'],
    },

    footer: {
      about: 'منصة دعم القرار لمزارعي الكرز في جهة فاس مكناس.',
      account: 'الحساب',
      register: 'إنشاء حساب مزارع',
      expert: 'طلب حساب خبير',
      sources: 'المصادر',
      sourceList: [
        { before: 'صورة القمر الصناعي: ', link: 'NASA Worldview', href: 'https://worldview.earthdata.nasa.gov/', after: '.' },
        { before: 'بيانات الطقس: ', link: 'Open-Meteo.com', href: 'https://open-meteo.com/', after: '.' },
      ],
    },
  },
};
